executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-iOS
    macos:
      xcode: 10.3.0
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: 2.6.3
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-iOS
    macos:
      xcode: 11.0.0
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: 2.6.3


version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceSDKCommon"
      device:
        type: string
        default: "iPhone XR"
      ios:
        type: string
        default: "12.4"
      nightly-test:
        type: boolean
        default: false
      env: 
        type: executor
        default: "mac"
    executor: << parameters.env >> 
    environment:
      LIB: << parameters.lib >> 
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      NIGHTLY_TEST: << parameters.nightly-test >>
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
            - v5-gems-
      - run: 
          name: Install Dependencies
          command:  |
            npm install shelljs@0.8.3
            ./install.sh
            ./build/pre-build
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle check || sudo bundle install
            sudo bundle update
      - save_cache: 
          key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/2.6.3
      - run: 
          name: Run Tests
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle exec fastlane PR lib:<< parameters.lib >> 
      - run: 
          name: Danger Lib
          command:  |
            chruby ${CHRUBY_VER}
            DANGER_GITHUB_API_TOKEN="279a29d75427e4178cef""b7b5b2d7646c540f025a" danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis
      - run: 
          name: Codecov Uplaod
          command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode
          when: always

      
workflows:
  version: 2

  build-test-pr:
    jobs:
      - run-tests:
          name: "SalesforceSDKCommon"
          lib: "SalesforceSDKCommon"
          filters:
            branches:
              only:
                - /pull.*/
      - run-tests:
          name: "SalesforceAnalytics"
          lib: "SalesforceAnalytics"
          filters:
            branches:
              only:
                - /pull.*/
      - run-tests:
          name: "SalesforceSDKCore"
          lib: "SalesforceSDKCore"
          filters:
            branches:
              only:
                - /pull.*/
      - run-tests:
          name: "SmartStore"
          lib: "SmartStore"
          filters:
            branches:
              only:
                - /pull.*/
      - run-tests:
          name: "SmartSync"
          lib: "SmartSync"
          filters:
            branches:
              only:
                - /pull.*/

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~9:30pm Tuesday/Thursday Nights
  nightly-test-ios11:
    triggers:
      - schedule:
          cron: "30 5 * * 3,5"
          filters:
            branches:
              only:
                - dev
    jobs:
      - run-tests:
          name: "SalesforceSDKCommon iOS 11 Nightly"
          lib: "SalesforceSDKCommon"
          device: "iPhone X"
          ios: "11.4"
          nightly-test: true
      - run-tests:
          name: "SalesforceAnalytics iOS 11 Nightly"
          lib: "SalesforceAnalytics"
          device: "iPhone X"
          ios: "11.4"
          nightly-test: true 
      - run-tests:
          name: "SalesforceSDKCore iOS 11 Nightly"
          lib: "SalesforceSDKCore"
          device: "iPhone X"
          ios: "11.4"
          nightly-test: true 
      - run-tests:
          name: "SmartStore iOS 11 Nightly"
          lib: "SmartStore"
          device: "iPhone X"
          ios: "11.4"
          nightly-test: true
      - run-tests:
          name: "SmartSync iOS 11 Nightly"
          lib: "SmartSync"
          device: "iPhone X"
          ios: "11.4"
          nightly-test: true

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~10:30pm Tuesday/Thursday Nights
  nightly-test-ios12:
    triggers:
      - schedule:
          cron: "30 6 * * 3,5"
          filters:
            branches:
              only:
                - dev
    jobs:
      - run-tests:
          name: "SalesforceSDKCommon iOS 12 Nightly"
          lib: "SalesforceSDKCommon"
          nightly-test: true
      - run-tests:
          name: "SalesforceAnalytics iOS 12 Nightly"
          lib: "SalesforceAnalytics"
          nightly-test: true 
      - run-tests:
          name: "SalesforceSDKCore iOS 12 Nightly"
          lib: "SalesforceSDKCore"
          nightly-test: true 
      - run-tests:
          name: "SmartStore iOS 12 Nightly"
          lib: "SmartStore"
          nightly-test: true
      - run-tests:
          name: "SmartSync iOS 12 Nightly"
          lib: "SmartSync"
          nightly-test: true

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~11:30am Tuesday/Thursday Nights
  nightly-test-ios13:
    triggers:
      - schedule:
          cron: "30 7 * * 3,5"
          filters:
            branches:
              only:
                - dev
    jobs:
      - run-tests:
          name: "SalesforceSDKCommon iOS 13 Nightly"
          lib: "SalesforceSDKCommon"
          nightly-test: true
          env: "mac-beta"
          ios: "13.0"
      - run-tests:
          name: "SalesforceAnalytics iOS 13 Nightly"
          lib: "SalesforceAnalytics"
          nightly-test: true 
          env: "mac-beta"
          ios: "13.0"
      - run-tests:
          name: "SalesforceSDKCore iOS 13 Nightly"
          lib: "SalesforceSDKCore"
          nightly-test: true 
          env: "mac-beta"
          ios: "13.0"
      - run-tests:
          name: "SmartStore iOS 13 Nightly"
          lib: "SmartStore"
          nightly-test: true
          env: "mac-beta"
          ios: "13.0"
      - run-tests:
          name: "SmartSync iOS 13 Nightly"
          lib: "SmartSync"
          nightly-test: true
          env: "mac-beta"
          ios: "13.0"